
package com.hikvision.ivms6.cms.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IAuthServicePortType", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IAuthServicePortType {


    /**
     * 
     * @param tgc
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:logout")
    @WebResult(targetNamespace = "http://ws.cms.ivms6.hikvision.com")
    @RequestWrapper(localName = "logout", targetNamespace = "http://ws.cms.ivms6.hikvision.com", className = "com.hikvision.ivms6.cms.ws.Logout")
    @ResponseWrapper(localName = "logoutResponse", targetNamespace = "http://ws.cms.ivms6.hikvision.com", className = "com.hikvision.ivms6.cms.ws.LogoutResponse")
    public String logout(
        @WebParam(name = "tgc", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
        String tgc);

    /**
     * 
     * @param st
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:verifyToken")
    @WebResult(targetNamespace = "http://ws.cms.ivms6.hikvision.com")
    @RequestWrapper(localName = "verifyToken", targetNamespace = "http://ws.cms.ivms6.hikvision.com", className = "com.hikvision.ivms6.cms.ws.VerifyToken")
    @ResponseWrapper(localName = "verifyTokenResponse", targetNamespace = "http://ws.cms.ivms6.hikvision.com", className = "com.hikvision.ivms6.cms.ws.VerifyTokenResponse")
    public String verifyToken(
        @WebParam(name = "st", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
        String st);

    /**
     * 
     * @param validity
     * @param st
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:applyAutoLogin")
    @WebResult(targetNamespace = "http://ws.cms.ivms6.hikvision.com")
    @RequestWrapper(localName = "applyAutoLogin", targetNamespace = "http://ws.cms.ivms6.hikvision.com", className = "com.hikvision.ivms6.cms.ws.ApplyAutoLogin")
    @ResponseWrapper(localName = "applyAutoLoginResponse", targetNamespace = "http://ws.cms.ivms6.hikvision.com", className = "com.hikvision.ivms6.cms.ws.ApplyAutoLoginResponse")
    public String applyAutoLogin(
        @WebParam(name = "st", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
        String st,
        @WebParam(name = "validity", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
        Integer validity);

    /**
     * 
     * @param ip
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:verifyServicePrivilege")
    @WebResult(targetNamespace = "http://ws.cms.ivms6.hikvision.com")
    @RequestWrapper(localName = "verifyServicePrivilege", targetNamespace = "http://ws.cms.ivms6.hikvision.com", className = "com.hikvision.ivms6.cms.ws.VerifyServicePrivilege")
    @ResponseWrapper(localName = "verifyServicePrivilegeResponse", targetNamespace = "http://ws.cms.ivms6.hikvision.com", className = "com.hikvision.ivms6.cms.ws.VerifyServicePrivilegeResponse")
    public String verifyServicePrivilege(
        @WebParam(name = "ip", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
        String ip);

    /**
     * 
     * @param operCode
     * @param st
     * @param indexCode
     * @param resType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:verifyTokenAndPrivilege")
    @WebResult(targetNamespace = "http://ws.cms.ivms6.hikvision.com")
    @RequestWrapper(localName = "verifyTokenAndPrivilege", targetNamespace = "http://ws.cms.ivms6.hikvision.com", className = "com.hikvision.ivms6.cms.ws.VerifyTokenAndPrivilege")
    @ResponseWrapper(localName = "verifyTokenAndPrivilegeResponse", targetNamespace = "http://ws.cms.ivms6.hikvision.com", className = "com.hikvision.ivms6.cms.ws.VerifyTokenAndPrivilegeResponse")
    public String verifyTokenAndPrivilege(
        @WebParam(name = "st", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
        String st,
        @WebParam(name = "resType", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
        Integer resType,
        @WebParam(name = "indexCode", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
        String indexCode,
        @WebParam(name = "operCode", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
        String operCode);

    /**
     * 
     * @param clientMac
     * @param serviceIp
     * @param clientIp
     * @param password
     * @param loginAccount
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:login")
    @WebResult(targetNamespace = "http://ws.cms.ivms6.hikvision.com")
    @RequestWrapper(localName = "login", targetNamespace = "http://ws.cms.ivms6.hikvision.com", className = "com.hikvision.ivms6.cms.ws.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://ws.cms.ivms6.hikvision.com", className = "com.hikvision.ivms6.cms.ws.LoginResponse")
    public String login(
        @WebParam(name = "loginAccount", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
        String loginAccount,
        @WebParam(name = "password", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
        String password,
        @WebParam(name = "serviceIp", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
        String serviceIp,
        @WebParam(name = "clientIp", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
        String clientIp,
        @WebParam(name = "clientMac", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
        String clientMac);

    /**
     * 
     * @param tgt
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:applyToken")
    @WebResult(targetNamespace = "http://ws.cms.ivms6.hikvision.com")
    @RequestWrapper(localName = "applyToken", targetNamespace = "http://ws.cms.ivms6.hikvision.com", className = "com.hikvision.ivms6.cms.ws.ApplyToken")
    @ResponseWrapper(localName = "applyTokenResponse", targetNamespace = "http://ws.cms.ivms6.hikvision.com", className = "com.hikvision.ivms6.cms.ws.ApplyTokenResponse")
    public String applyToken(
        @WebParam(name = "tgt", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
        String tgt);

    /**
     * 
     * @param st
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:loginBySt")
    @WebResult(targetNamespace = "http://ws.cms.ivms6.hikvision.com")
    @RequestWrapper(localName = "loginBySt", targetNamespace = "http://ws.cms.ivms6.hikvision.com", className = "com.hikvision.ivms6.cms.ws.LoginBySt")
    @ResponseWrapper(localName = "loginByStResponse", targetNamespace = "http://ws.cms.ivms6.hikvision.com", className = "com.hikvision.ivms6.cms.ws.LoginByStResponse")
    public String loginBySt(
        @WebParam(name = "st", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
        String st);

    /**
     * 
     * @param tgt
     * @param url
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:applyTokenByUrl")
    @WebResult(targetNamespace = "http://ws.cms.ivms6.hikvision.com")
    @RequestWrapper(localName = "applyTokenByUrl", targetNamespace = "http://ws.cms.ivms6.hikvision.com", className = "com.hikvision.ivms6.cms.ws.ApplyTokenByUrl")
    @ResponseWrapper(localName = "applyTokenByUrlResponse", targetNamespace = "http://ws.cms.ivms6.hikvision.com", className = "com.hikvision.ivms6.cms.ws.ApplyTokenByUrlResponse")
    public String applyTokenByUrl(
        @WebParam(name = "tgt", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
        String tgt,
        @WebParam(name = "url", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
        String url);

    /**
     * 
     * @param autoLoginSession
     * @param serviceIp
     * @param clientmac
     * @param clientIp
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:autoLogin")
    @WebResult(targetNamespace = "http://ws.cms.ivms6.hikvision.com")
    @RequestWrapper(localName = "autoLogin", targetNamespace = "http://ws.cms.ivms6.hikvision.com", className = "com.hikvision.ivms6.cms.ws.AutoLogin")
    @ResponseWrapper(localName = "autoLoginResponse", targetNamespace = "http://ws.cms.ivms6.hikvision.com", className = "com.hikvision.ivms6.cms.ws.AutoLoginResponse")
    public String autoLogin(
        @WebParam(name = "autoLoginSession", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
        String autoLoginSession,
        @WebParam(name = "clientmac", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
        String clientmac,
        @WebParam(name = "clientIp", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
        String clientIp,
        @WebParam(name = "serviceIp", targetNamespace = "http://ws.cms.ivms6.hikvision.com")
        String serviceIp);

}
