
package com.hikvision.ivms6.cms.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "IAuthService", targetNamespace = "http://ws.cms.ivms6.hikvision.com", wsdlLocation = "http://119.1.223.145:801/cms/services/IAuthService?wsdl")
public class IAuthService
    extends Service
{

    private final static URL IAUTHSERVICE_WSDL_LOCATION;
    private final static WebServiceException IAUTHSERVICE_EXCEPTION;
    private final static QName IAUTHSERVICE_QNAME = new QName("http://ws.cms.ivms6.hikvision.com", "IAuthService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://119.1.223.145:801/cms/services/IAuthService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IAUTHSERVICE_WSDL_LOCATION = url;
        IAUTHSERVICE_EXCEPTION = e;
    }

    public IAuthService() {
        super(__getWsdlLocation(), IAUTHSERVICE_QNAME);
    }

    public IAuthService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IAUTHSERVICE_QNAME, features);
    }

    public IAuthService(URL wsdlLocation) {
        super(wsdlLocation, IAUTHSERVICE_QNAME);
    }

    public IAuthService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IAUTHSERVICE_QNAME, features);
    }

    public IAuthService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IAuthService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IAuthServicePortType
     */
    @WebEndpoint(name = "IAuthServiceHttpSoap11Endpoint")
    public IAuthServicePortType getIAuthServiceHttpSoap11Endpoint() {
        return super.getPort(new QName("http://ws.cms.ivms6.hikvision.com", "IAuthServiceHttpSoap11Endpoint"), IAuthServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAuthServicePortType
     */
    @WebEndpoint(name = "IAuthServiceHttpSoap11Endpoint")
    public IAuthServicePortType getIAuthServiceHttpSoap11Endpoint(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.cms.ivms6.hikvision.com", "IAuthServiceHttpSoap11Endpoint"), IAuthServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IAUTHSERVICE_EXCEPTION!= null) {
            throw IAUTHSERVICE_EXCEPTION;
        }
        return IAUTHSERVICE_WSDL_LOCATION;
    }

}
